/* tslint:disable */
/* eslint-disable */
/**
 * Social Service
 * Solomon AI Social Service
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BlockUserProfileResponse,
  InternalErrorMessageResponse,
  PathUnknownErrorMessageResponse,
  Status,
  ValidationErrorMessageResponse,
} from '../models/index';
import {
    BlockUserProfileResponseFromJSON,
    BlockUserProfileResponseToJSON,
    InternalErrorMessageResponseFromJSON,
    InternalErrorMessageResponseToJSON,
    PathUnknownErrorMessageResponseFromJSON,
    PathUnknownErrorMessageResponseToJSON,
    StatusFromJSON,
    StatusToJSON,
    ValidationErrorMessageResponseFromJSON,
    ValidationErrorMessageResponseToJSON,
} from '../models/index';

export interface BlockUserProfileRequest {
    sourceUserId: string;
    targetUserId: string;
}

/**
 * 
 */
export class BlockProfileApi extends runtime.BaseAPI {

    /**
     * This endpoint enables a client to block a user profile
     * blocks a user profile
     */
    async blockUserProfileRaw(requestParameters: BlockUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BlockUserProfileResponse>> {
        if (requestParameters.sourceUserId === null || requestParameters.sourceUserId === undefined) {
            throw new runtime.RequiredError('sourceUserId','Required parameter requestParameters.sourceUserId was null or undefined when calling blockUserProfile.');
        }

        if (requestParameters.targetUserId === null || requestParameters.targetUserId === undefined) {
            throw new runtime.RequiredError('targetUserId','Required parameter requestParameters.targetUserId was null or undefined when calling blockUserProfile.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/users/source/{sourceUserId}/block/target/{targetUserId}`.replace(`{${"sourceUserId"}}`, encodeURIComponent(String(requestParameters.sourceUserId))).replace(`{${"targetUserId"}}`, encodeURIComponent(String(requestParameters.targetUserId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BlockUserProfileResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint enables a client to block a user profile
     * blocks a user profile
     */
    async blockUserProfile(requestParameters: BlockUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BlockUserProfileResponse> {
        const response = await this.blockUserProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
