/* tslint:disable */
/* eslint-disable */
/**
 * Social Service
 * Solomon AI Social Service
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetBookmarkedPostsResponse,
  InternalErrorMessageResponse,
  PathUnknownErrorMessageResponse,
  Status,
  ValidationErrorMessageResponse,
} from '../models/index';
import {
    GetBookmarkedPostsResponseFromJSON,
    GetBookmarkedPostsResponseToJSON,
    InternalErrorMessageResponseFromJSON,
    InternalErrorMessageResponseToJSON,
    PathUnknownErrorMessageResponseFromJSON,
    PathUnknownErrorMessageResponseToJSON,
    StatusFromJSON,
    StatusToJSON,
    ValidationErrorMessageResponseFromJSON,
    ValidationErrorMessageResponseToJSON,
} from '../models/index';

export interface GetBookmarkedPostsRequest {
    userId: string;
}

/**
 * 
 */
export class BookmarksApi extends runtime.BaseAPI {

    /**
     * This endpoint enables a client to get all bookmarked posts of a given user
     * Get Bookmarked Posts
     */
    async getBookmarkedPostsRaw(requestParameters: GetBookmarkedPostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBookmarkedPostsResponse>> {
        if (requestParameters.userId === null || requestParameters.userId === undefined) {
            throw new runtime.RequiredError('userId','Required parameter requestParameters.userId was null or undefined when calling getBookmarkedPosts.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/users/bookmarks/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters.userId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBookmarkedPostsResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint enables a client to get all bookmarked posts of a given user
     * Get Bookmarked Posts
     */
    async getBookmarkedPosts(requestParameters: GetBookmarkedPostsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBookmarkedPostsResponse> {
        const response = await this.getBookmarkedPostsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
