/* tslint:disable */
/* eslint-disable */
/**
 * Social Service
 * Solomon AI Social Service
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FollowCommunityProfileResponse,
  InternalErrorMessageResponse,
  PathUnknownErrorMessageResponse,
  Status,
  ValidationErrorMessageResponse,
} from '../models/index';
import {
    FollowCommunityProfileResponseFromJSON,
    FollowCommunityProfileResponseToJSON,
    InternalErrorMessageResponseFromJSON,
    InternalErrorMessageResponseToJSON,
    PathUnknownErrorMessageResponseFromJSON,
    PathUnknownErrorMessageResponseToJSON,
    StatusFromJSON,
    StatusToJSON,
    ValidationErrorMessageResponseFromJSON,
    ValidationErrorMessageResponseToJSON,
} from '../models/index';

export interface FollowCommunityProfileRequest {
    sourceUserId: string;
    targetCommunityProfileId: string;
}

/**
 * 
 */
export class FollowCommunityProfileApi extends runtime.BaseAPI {

    /**
     * This endpoint enables a client to follow a community profile
     * Follows A Community Profile
     */
    async followCommunityProfileRaw(requestParameters: FollowCommunityProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FollowCommunityProfileResponse>> {
        if (requestParameters.sourceUserId === null || requestParameters.sourceUserId === undefined) {
            throw new runtime.RequiredError('sourceUserId','Required parameter requestParameters.sourceUserId was null or undefined when calling followCommunityProfile.');
        }

        if (requestParameters.targetCommunityProfileId === null || requestParameters.targetCommunityProfileId === undefined) {
            throw new runtime.RequiredError('targetCommunityProfileId','Required parameter requestParameters.targetCommunityProfileId was null or undefined when calling followCommunityProfile.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/users/source/{sourceUserId}/follow/community-profiles/{targetCommunityProfileId}`.replace(`{${"sourceUserId"}}`, encodeURIComponent(String(requestParameters.sourceUserId))).replace(`{${"targetCommunityProfileId"}}`, encodeURIComponent(String(requestParameters.targetCommunityProfileId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FollowCommunityProfileResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint enables a client to follow a community profile
     * Follows A Community Profile
     */
    async followCommunityProfile(requestParameters: FollowCommunityProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FollowCommunityProfileResponse> {
        const response = await this.followCommunityProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
