/* tslint:disable */
/* eslint-disable */
/**
 * Social Service
 * Solomon AI Social Service
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTeamResponse
 */
export interface CreateTeamResponse {
    /**
     * The ID of the newly created team.
     * @type {string}
     * @memberof CreateTeamResponse
     */
    teamId?: string;
}

/**
 * Check if a given object implements the CreateTeamResponse interface.
 */
export function instanceOfCreateTeamResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateTeamResponseFromJSON(json: any): CreateTeamResponse {
    return CreateTeamResponseFromJSONTyped(json, false);
}

export function CreateTeamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTeamResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'teamId': !exists(json, 'teamId') ? undefined : json['teamId'],
    };
}

export function CreateTeamResponseToJSON(value?: CreateTeamResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'teamId': value.teamId,
    };
}

