/* tslint:disable */
/* eslint-disable */
/**
 * Social Service
 * Solomon AI Social Service
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserProfile } from './UserProfile';
import {
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
} from './UserProfile';

/**
 * 
 * @export
 * @interface GetTeamMemberResponse
 */
export interface GetTeamMemberResponse {
    /**
     * 
     * @type {UserProfile}
     * @memberof GetTeamMemberResponse
     */
    member?: UserProfile;
}

/**
 * Check if a given object implements the GetTeamMemberResponse interface.
 */
export function instanceOfGetTeamMemberResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetTeamMemberResponseFromJSON(json: any): GetTeamMemberResponse {
    return GetTeamMemberResponseFromJSONTyped(json, false);
}

export function GetTeamMemberResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTeamMemberResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'member': !exists(json, 'member') ? undefined : UserProfileFromJSON(json['member']),
    };
}

export function GetTeamMemberResponseToJSON(value?: GetTeamMemberResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'member': UserProfileToJSON(value.member),
    };
}

