/* tslint:disable */
/* eslint-disable */
/**
 * Social Service
 * Solomon AI Social Service
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserProfile } from './UserProfile';
import {
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
} from './UserProfile';

/**
 * 
 * @export
 * @interface GetTeamMembersResponse
 */
export interface GetTeamMembersResponse {
    /**
     * A list of team member profile objects containing details about the team members.
     * @type {Array<UserProfile>}
     * @memberof GetTeamMembersResponse
     */
    members?: Array<UserProfile>;
}

/**
 * Check if a given object implements the GetTeamMembersResponse interface.
 */
export function instanceOfGetTeamMembersResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetTeamMembersResponseFromJSON(json: any): GetTeamMembersResponse {
    return GetTeamMembersResponseFromJSONTyped(json, false);
}

export function GetTeamMembersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTeamMembersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'members': !exists(json, 'members') ? undefined : ((json['members'] as Array<any>).map(UserProfileFromJSON)),
    };
}

export function GetTeamMembersResponseToJSON(value?: GetTeamMembersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'members': value.members === undefined ? undefined : ((value.members as Array<any>).map(UserProfileToJSON)),
    };
}

