/* tslint:disable */
/* eslint-disable */
/**
 * Social Service
 * Solomon AI Social Service
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TeamProfile } from './TeamProfile';
import {
    TeamProfileFromJSON,
    TeamProfileFromJSONTyped,
    TeamProfileToJSON,
} from './TeamProfile';

/**
 * 
 * @export
 * @interface GetTeamResponse
 */
export interface GetTeamResponse {
    /**
     * 
     * @type {TeamProfile}
     * @memberof GetTeamResponse
     */
    team?: TeamProfile;
}

/**
 * Check if a given object implements the GetTeamResponse interface.
 */
export function instanceOfGetTeamResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetTeamResponseFromJSON(json: any): GetTeamResponse {
    return GetTeamResponseFromJSONTyped(json, false);
}

export function GetTeamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTeamResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'team': !exists(json, 'team') ? undefined : TeamProfileFromJSON(json['team']),
    };
}

export function GetTeamResponseToJSON(value?: GetTeamResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'team': TeamProfileToJSON(value.team),
    };
}

